### ISSUE TITLE
the unpkg not working as intended.

### ISSUE THREAD

**Issue by BIntelligent** [Danktuary/wc-discord-message#3]
![Screenshot - 11_16_2020 , 8_53_46 PM](https://user-images.githubusercontent.com/65684589/99306969-bb2cee00-280a-11eb-9edb-4c36d67ea971.png)
this  unpkg is not working..... and please can you make a example with html only.. like no renderer or any of that stuff, or in ejs, like a small example that i can upload on my host and it works.. Thanks!

**Comment by Danktuary** [comment]
Sorry about that; it was because that way of referencing the browser build file is incorrect. I copied over the readme from my other project and overlooked that. I fixed this in v2.0.2, you should now reference it as:
```html
<script src="https://unpkg.com/wc-discord-message@^2.0.0/dist/wc-discord-message/wc-discord-message.js"></script>
```
As for further examples, you should check the [demo site](https://wc-discord-message.netlify.com/) and the [src/index.html](https://github.com/Danktuary/wc-discord-message/blob/master/src/index.html) file. You can copy the entire index.html file, just replace these 2 lines with the one above:
```html
<script type="module" src="/build/wc-discord-message.esm.js"></script>
<script nomodule src="/build/wc-discord-message.js"></script>
```
